apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  namespace: movie
spec:
  storageClassName: "oci-bv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
